### ISSUE TITLE
Klikatelnost itemů

### ISSUE THREAD

**Issue by VojtechVidra** [keombre/progtest-theme#10]
Díky material theme jsem 9x produktivnější. Kdybych věděl na kterou položku v menu můžu kliknout, tak bych byl 10x produktivnější. V originálním theme vidím button u otevřených úloh, ale v material theme nerozpoznám který item je klikatelný, pouze po přejetí myši.

**Comment by keombre** [comment]
implemented in version 1.0.21 9173c887756bad8f42e022071e794c8b10dc59b0
