### ISSUE TITLE
Missed point

### ISSUE THREAD

**Issue by NeoMorphius** [keombre/progtest-theme#15]
![issue](https://user-images.githubusercontent.com/31204939/67726105-0b10fb00-f9e5-11e9-8f86-3b148b89b004.jpg)

**Comment by keombre** [comment]
Could you please attach HTML of that page?
It would make replicating the issue much simpler.
Thx.

**Comment by NeoMorphius** [comment]
[bug.zip](https://github.com/keombre/progtest-theme/files/3790337/bug.zip)

**Comment by NeoMorphius** [comment]
[bug2.zip](https://github.com/keombre/progtest-theme/files/3790348/bug2.zip)
