### ISSUE TITLE
Add option to disable emoji-like numbers on submitted solution.

### ISSUE THREAD

**Issue by ingdanko** [keombre/progtest-theme#22]
Title.

I personally find the emoji use everywhere else a nice addition, but in the submits, they take away readability. A toggle would be perfect.

**Comment by keombre** [comment]
This was not intended. Again waiting for Google to review new release.
see commit [dc0c3af23](https://github.com/keombre/progtest-theme/commit/dc0c3af23d8cfd612fa6a2bce711c9fccc6fe263)

Here is how it is supposed to look like:
![image](https://user-images.githubusercontent.com/25846387/76163600-c42bd280-6147-11ea-97cc-c6fcafba6218.png)

**Comment by keombre** [comment]
version 1.0.35 is out
