### ISSUE TITLE
Dark mode background color make images unreadable.

### ISSUE THREAD

**Issue by ingdanko** [keombre/progtest-theme#23]
Title.

Screenshots:
![image](https://user-images.githubusercontent.com/20192832/76162581-5b405c80-613f-11ea-8f3f-e033272b93f3.png)
![image](https://user-images.githubusercontent.com/20192832/76162585-62676a80-613f-11ea-972e-a259e7acb68f.png)

This is not the only place where it happens, it's happened to me a few times already. Not sure if removing the background-color would cause problems elsewhere.

**Comment by ingdanko** [comment]
Ok, I checked all other assignments, and couldn't find another instance of this happening. Idk what the correct approach is here.

**Comment by keombre** [comment]
yea, this is already fixed, just waiting for google to publish new patch
see commit [dc0c3af23](https://github.com/keombre/progtest-theme/commit/dc0c3af23d8cfd612fa6a2bce711c9fccc6fe263)

**Comment by keombre** [comment]
version 1.0.35 is out
