### ISSUE TITLE
Nelze spustit znalostni test

### ISSUE THREAD

**Issue by hejdamax** [keombre/progtest-theme#25]
Po kliknuti na znalostni test se nic nedeje... Pouzivam dark skin a kdyz si chci zobrazit znalostni test tak musim prepnout na default skin.

**Comment by keombre** [comment]
Mohl by jsi prosím přiložit screenshot/výstup z debug konzole chromu, verzi chromu a OS
Jinak bohužel nemám jak problém reprodukovat

**Comment by hejdamax** [comment]
Ahoj pouzivam mozillu verze 72.0.1 (64-bit) OS ubuntu 19.04 a vystup poslu pri tretim testu... Chyba se projevi pouze pri prvnim otevirani testu.... Dole jak se objevuje preview linku je napsana ta hlaska jestli chci spustit test a kdyz kliknu nic na me nevyskoci (ma vyskocit to okenko: opravdu chcete spustit test).

**Comment by mstieranka** [comment]
V Mozilla Firefox 75.0 (x64) mám ten istý problém. Skúsil som nejaký troubleshooting a vypadá to na problém s https://github.com/keombre/progtest-theme/blob/4495e2e0d66bbf8f5752bea375e962c78251cd15/src/content/end.js#L925

Po zavolaní tejto funkcie sa URL nezmení (tj. nespustí sa `javascript:` link). Zaujímavé ale je, že keď v konzole ručne zavolám `window.location.assign("javascript:...")`, tak všetko funguje podľa očakávaní.

Samotný link, ktorý je problematický, je `javascript:if(confirm('Chcete zadat tento test? Od okamžiku zadání budete mít na vypracování celkem 15 minut.')){this.location='?X=KNT&amp;Cou=292&amp;Knt=1128'}`.

V prehliadači Chromium 81.0.4044.113 zavolanie `assign()` po kliknutí na test funguje.

**Comment by keombre** [comment]
Nový release je už na cestě. Pro FF by měl být ještě dneska, ale deploy do Chrome webstore a MS Edge store bohužel trvá několik dní.
