### ISSUE TITLE
When icon clicked while on a blank tab, open link in the blank one, instead of creating a new tab.

### ISSUE THREAD

**Issue by ingdanko** [keombre/progtest-theme#28]
Title.

Currently, if the extension icon is clicked, a new tab pops up with progtest.fit.cvut.cz. But even on  blank tabs, a new one opens, leaving the user with two tabs, one of which is blank.

A good example of this hurting user experience is when the browser is opened, and the user has a blank page as the default page. Clicking on the extension icon now doesn't take him to progtest directly, but instead leaves him with an unnecessary blank tab.

**Comment by keombre** [comment]
closed by #29
