### ISSUE TITLE
When using Progtest themes, some tests are not available

### ISSUE THREAD

**Issue by MasterVotr** [keombre/progtest-theme#35]
When I tried to open a test from a subject (BI-PYT), I wasn't able to. It looked like the test wasn't open yet and I cound not *click* on it. When I switched Progtest Themes off I was able to accesss it.

![PT_on](https://user-images.githubusercontent.com/24864413/97165407-ee3c0e80-1783-11eb-8691-ef0905c8ea59.png)
![PT_off](https://user-images.githubusercontent.com/24864413/97165493-0f046400-1784-11eb-94bc-5d20e6d556d4.png)

**Comment by keombre** [comment]
Could you please post the HTML?
Also what version of the extension are you using? In chrome, the lastest is 1.1.5 where I thought I had fixed this.

**Comment by keombre** [comment]
Should be fixed in 97e3cb9c6154413fdf407984af08e8cf9b4f02c0

**Comment by keombre** [comment]
Ok, new version is out (1.1.6)
Could you please report back if the fix worked?
