### ISSUE TITLE
Wrong score displayed in PA1.

### ISSUE THREAD

**Issue by adamhradil** [keombre/progtest-theme#36]
Score doesn't match with the corresponding task. Probably caused by new task names introduced in PA1.

![Screenshot_49](https://user-images.githubusercontent.com/24945561/97165791-8b974280-1784-11eb-9107-85a542163538.png)
![Screenshot_50](https://user-images.githubusercontent.com/24945561/97165793-8c2fd900-1784-11eb-86c3-b82ae58ed3c3.png)

**Comment by keombre** [comment]
All of this is related to the usage of the new Progtest API.
I'll try to fix this as soon as possible.

**Comment by keombre** [comment]
Should be fixed in 97e3cb9c6154413fdf407984af08e8cf9b4f02c0
