### ISSUE TITLE
Referenční řešení cannot be open

### ISSUE THREAD

**Issue by tenhobi** [keombre/progtest-theme#4]
Tab 'Referenční řešení' cannot be open with a click as solutions below.

![image](https://user-images.githubusercontent.com/5287596/58492787-eb458480-8171-11e9-8e20-65f10ccf2da0.png)

**Comment by keombre** [comment]
This was a deliberate decision. There already is an event listener bound to the checkbox (next to tab title) from Mr. Vagner. Therefore I didn't want to add another collapsing script to that element.

The solution might be to rebind the original EL to the whole tab, but that will need more testing.

**Comment by keombre** [comment]
Implemented in d08c0a1

**Comment by keombre** [comment]
The feature seems stable enough.
