### ISSUE TITLE
Code review not clickable when theme is changed

### ISSUE THREAD

**Issue by GBoGH** [keombre/progtest-theme#54]
When the theme is changed, Code Review field isnt clickable nor is it showing any results. Doesnt matter whether the theme is light or dark.
![image](https://user-images.githubusercontent.com/44493112/210431826-bfebfab2-87a4-4ac6-b51e-8706d8e07078.png)

On the original theme code review is accessible
![image](https://user-images.githubusercontent.com/44493112/210431910-c9302725-23f7-4eb0-b30a-87aef3e24207.png)

The code review page is accessible using the url and it works well, it just doesn't show up on the home page.

Doesnt work in Mozilla either

**Comment by mstieranka** [comment]
Hey, can you share the HTML of both this page and the code review in the original theme? I'll look into it and try to make it work, but I don't have any one of these new code reviews available.

**Comment by mstieranka** [comment]
Release will be out in the next 24 hours, but it may not update so fast on your end.

First, I need to wait for the original maintainer to click "Agree" on a new Firefox policy to be able to release it, then if you're on Chrome, you'll need to wait for the store entry to get approved. Alternatively, you'll be able to update directly from this repo. I'll update with a link to the downloads once relevant.

**Comment by keombre** [comment]
https://github.com/keombre/progtest-theme/issues/56#issuecomment-1774696400

**Comment by mstieranka** [comment]
[The release is out, this issue should now be fixed.](https://github.com/keombre/progtest-theme/releases/tag/v1.2.0)
