### ISSUE TITLE
Unable to access current progtests

### ISSUE THREAD

**Issue by love-vinegar** [keombre/progtest-theme#56]
Im experiencing this bug where im not able to access the already accesable progtests. 
![image](https://github.com/keombre/progtest-theme/assets/54249550/95534c7d-dbda-466f-9c26-fbcf006f2b77)
when i turn off this extention the progtest is normally accesable
![image](https://github.com/keombre/progtest-theme/assets/54249550/c38aadb4-b4db-4b27-ac19-01fbee9ea553)

im on firefox and the console has these errors
![image](https://github.com/keombre/progtest-theme/assets/54249550/83e07574-abb2-4158-8306-85136a5661e1)

**Comment by leukk** [comment]
+1, having the exact same issue

**Comment by mstieranka** [comment]
Thanks for letting me know! Seems like not too long ago, the [+] button got added into the deadline field, which breaks the extension (since it's only expecting one button which would open the Progtest).

I'll try and fix this (releasing is a bit of a different beast, since I took over from the original maintainer and haven't done an official release yet, but it should not be that much of an issue).

**Comment by mstieranka** [comment]
Release will be out in the next 24 hours, but it may not update so fast on your end.

First, I need to wait for the original maintainer to click "Agree" on a new Firefox policy to be able to release it, then if you're on Chrome, you'll need to wait for the store entry to get approved. Alternatively, you'll be able to update directly from this repo. I'll update with a link to the downloads once relevant.

**Comment by keombre** [comment]
I've updated Firefox Developer Hub permissions to make `progtest-themes` a group project. @mstieranka You should now be able to release without any complications.

Also, hats off with the latest release. It's a massive upgrade compared to the previous mess.
Good job!

**Comment by mstieranka** [comment]
[The release is out, this issue should now be fixed.](https://github.com/keombre/progtest-theme/releases/tag/v1.2.0)
