### ISSUE TITLE
Content width

### ISSUE THREAD

**Issue by Darxeal** [keombre/progtest-theme#6]
The page content width is way too large on large screens (like 1920px). It makes the tasks hard to read, and in the menus, the titles and their respective "Zobrazit" buttons are very far from each other.

I'd suggest to set the page content width to something like 1000-1200px.

**Comment by keombre** [comment]
I would like to rearrange virtually all pages. There should be an update coming in a couple of days which will change the layout of the course selection page.

Here is a little teaser:
![image](https://user-images.githubusercontent.com/25846387/59207804-0d92c580-8ba8-11e9-879f-e6b95071d6b9.png)
