### ISSUE TITLE
Better countdown

### ISSUE THREAD

**Issue by Darxeal** [keombre/progtest-theme#8]
In the task page, the countdown shows seconds, for example "727437.710 sec". This is very unreadable in my opinion, it would be better to format it like "A days, B hours, C minutes, D seconds" or something similiar.

**Comment by keombre** [comment]
You have no idea, how painstakingly difficult this was to implement. 😅 

![image](https://user-images.githubusercontent.com/25846387/66259770-c4e5c480-e7b5-11e9-8eca-9689a48352f5.png)

**Comment by Darxeal** [comment]
I think I do have an idea 😄 Nice work!

**Comment by keombre** [comment]
closed in 70e2234161ad00d93bf368f93b516124c5d31374
